//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMT05500FrontResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LMT05500FrontResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LMT05500FrontResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LMT05500FrontResources.LMT05500FrontResources_msgrsc", typeof(LMT05500FrontResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment.
        /// </summary>
        internal static string _Adj {
            get {
                return ResourceManager.GetString("_Adj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement Unit(s).
        /// </summary>
        internal static string _AggUnit {
            get {
                return ResourceManager.GetString("_AggUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement List.
        /// </summary>
        internal static string _AgreementList {
            get {
                return ResourceManager.GetString("_AgreementList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agreement No.
        /// </summary>
        internal static string _AgreementNo {
            get {
                return ResourceManager.GetString("_AgreementNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string _Amount {
            get {
                return ResourceManager.GetString("_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Rate.
        /// </summary>
        internal static string _BaseRate {
            get {
                return ResourceManager.GetString("_BaseRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustment.
        /// </summary>
        internal static string _btnAdj {
            get {
                return ResourceManager.GetString("_btnAdj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Note.
        /// </summary>
        internal static string _btnCreditNote {
            get {
                return ResourceManager.GetString("_btnCreditNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund.
        /// </summary>
        internal static string _btnRefund {
            get {
                return ResourceManager.GetString("_btnRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building.
        /// </summary>
        internal static string _Building {
            get {
                return ResourceManager.GetString("_Building", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        internal static string _Common {
            get {
                return ResourceManager.GetString("_Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractor.
        /// </summary>
        internal static string _Contractor {
            get {
                return ResourceManager.GetString("_Contractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string _CreatedBy {
            get {
                return ResourceManager.GetString("_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        internal static string _CreatedDate {
            get {
                return ResourceManager.GetString("_CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Note.
        /// </summary>
        internal static string _CreditNote {
            get {
                return ResourceManager.GetString("_CreditNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string _Currency {
            get {
                return ResourceManager.GetString("_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Rate.
        /// </summary>
        internal static string _CurrencyRate {
            get {
                return ResourceManager.GetString("_CurrencyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit.
        /// </summary>
        internal static string _Dep {
            get {
                return ResourceManager.GetString("_Dep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit Amount.
        /// </summary>
        internal static string _DepAmount {
            get {
                return ResourceManager.GetString("_DepAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposite Amount*.
        /// </summary>
        internal static string _DepAmount_ {
            get {
                return ResourceManager.GetString("_DepAmount*", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit Date.
        /// </summary>
        internal static string _DepDate {
            get {
                return ResourceManager.GetString("_DepDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit Date*.
        /// </summary>
        internal static string _DepDate_ {
            get {
                return ResourceManager.GetString("_DepDate*", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit Id.
        /// </summary>
        internal static string _DepId {
            get {
                return ResourceManager.GetString("_DepId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposti Id*.
        /// </summary>
        internal static string _DepId_ {
            get {
                return ResourceManager.GetString("_DepId*", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit Info.
        /// </summary>
        internal static string _DepInfo {
            get {
                return ResourceManager.GetString("_DepInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit List.
        /// </summary>
        internal static string _DepList {
            get {
                return ResourceManager.GetString("_DepList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit Name.
        /// </summary>
        internal static string _DepName {
            get {
                return ResourceManager.GetString("_DepName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string _Dept {
            get {
                return ResourceManager.GetString("_Dept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit Type.
        /// </summary>
        internal static string _DepType {
            get {
                return ResourceManager.GetString("_DepType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string _Desc {
            get {
                return ResourceManager.GetString("_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document No.
        /// </summary>
        internal static string _Doc {
            get {
                return ResourceManager.GetString("_Doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Date.
        /// </summary>
        internal static string _DocDate {
            get {
                return ResourceManager.GetString("_DocDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        internal static string _EndDate {
            get {
                return ResourceManager.GetString("_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        internal static string _Floor {
            get {
                return ResourceManager.GetString("_Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross.
        /// </summary>
        internal static string _Gross {
            get {
                return ResourceManager.GetString("_Gross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice No.
        /// </summary>
        internal static string _InvNo {
            get {
                return ResourceManager.GetString("_InvNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net.
        /// </summary>
        internal static string _Net {
            get {
                return ResourceManager.GetString("_Net", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment.
        /// </summary>
        internal static string _Pay {
            get {
                return ResourceManager.GetString("_Pay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Status.
        /// </summary>
        internal static string _PayStatus {
            get {
                return ResourceManager.GetString("_PayStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROPERTY.
        /// </summary>
        internal static string _Prop {
            get {
                return ResourceManager.GetString("_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref Date.
        /// </summary>
        internal static string _RefDate {
            get {
                return ResourceManager.GetString("_RefDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ref No.
        /// </summary>
        internal static string _RefNo {
            get {
                return ResourceManager.GetString("_RefNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refund.
        /// </summary>
        internal static string _Refund {
            get {
                return ResourceManager.GetString("_Refund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Amount.
        /// </summary>
        internal static string _RemainingAmt {
            get {
                return ResourceManager.GetString("_RemainingAmt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seq No.
        /// </summary>
        internal static string _SeqNo {
            get {
                return ResourceManager.GetString("_SeqNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        internal static string _StartDate {
            get {
                return ResourceManager.GetString("_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string _Status {
            get {
                return ResourceManager.GetString("_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant.
        /// </summary>
        internal static string _Tenant {
            get {
                return ResourceManager.GetString("_Tenant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trx Code.
        /// </summary>
        internal static string _TrxCode {
            get {
                return ResourceManager.GetString("_TrxCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string _Type {
            get {
                return ResourceManager.GetString("_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Desciption.
        /// </summary>
        internal static string _UnitDesc {
            get {
                return ResourceManager.GetString("_UnitDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Id.
        /// </summary>
        internal static string _UnitId {
            get {
                return ResourceManager.GetString("_UnitId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Type.
        /// </summary>
        internal static string _UnitType {
            get {
                return ResourceManager.GetString("_UnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update By.
        /// </summary>
        internal static string _UpdBy {
            get {
                return ResourceManager.GetString("_UpdBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Date.
        /// </summary>
        internal static string _UpdDate {
            get {
                return ResourceManager.GetString("_UpdDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string _View {
            get {
                return ResourceManager.GetString("_View", resourceCulture);
            }
        }
    }
}
