//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lookup_GSFrontResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Lookup_GSFrontResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lookup_GSFrontResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Lookup_GSFrontResources.Lookup_GSFrontResources_msgrsc", typeof(Lookup_GSFrontResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        internal static string _AccountName {
            get {
                return ResourceManager.GetString("_AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No.
        /// </summary>
        internal static string _AccountNo {
            get {
                return ResourceManager.GetString("_AccountNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string _Active {
            get {
                return ResourceManager.GetString("_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual.
        /// </summary>
        internal static string _Actual {
            get {
                return ResourceManager.GetString("_Actual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Code.
        /// </summary>
        internal static string _BankCode {
            get {
                return ResourceManager.GetString("_BankCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Name.
        /// </summary>
        internal static string _BankName {
            get {
                return ResourceManager.GetString("_BankName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Curr. Base Rate.
        /// </summary>
        internal static string _BaseCurrBaseRate {
            get {
                return ResourceManager.GetString("_BaseCurrBaseRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Currency Rate.
        /// </summary>
        internal static string _BaseCurrRate {
            get {
                return ResourceManager.GetString("_BaseCurrRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BS/IS.
        /// </summary>
        internal static string _BSISDesc {
            get {
                return ResourceManager.GetString("_BSISDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building ID.
        /// </summary>
        internal static string _BuildingId {
            get {
                return ResourceManager.GetString("_BuildingId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building Name.
        /// </summary>
        internal static string _BuildingName {
            get {
                return ResourceManager.GetString("_BuildingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string _CancelBtn {
            get {
                return ResourceManager.GetString("_CancelBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Flow Code.
        /// </summary>
        internal static string _CashFlowCode {
            get {
                return ResourceManager.GetString("_CashFlowCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Flow Group.
        /// </summary>
        internal static string _CashFlowGrp {
            get {
                return ResourceManager.GetString("_CashFlowGrp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Flow Group Id.
        /// </summary>
        internal static string _CashFlowGrpId {
            get {
                return ResourceManager.GetString("_CashFlowGrpId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Flow Group Name.
        /// </summary>
        internal static string _CashFlowGrpName {
            get {
                return ResourceManager.GetString("_CashFlowGrpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Flow Group Type.
        /// </summary>
        internal static string _CashFlowGrpType {
            get {
                return ResourceManager.GetString("_CashFlowGrpType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Flow Name.
        /// </summary>
        internal static string _CashFlowName {
            get {
                return ResourceManager.GetString("_CashFlowName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Flow Type.
        /// </summary>
        internal static string _CashFlowType {
            get {
                return ResourceManager.GetString("_CashFlowType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Code.
        /// </summary>
        internal static string _CenterCode {
            get {
                return ResourceManager.GetString("_CenterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Name.
        /// </summary>
        internal static string _CenterName {
            get {
                return ResourceManager.GetString("_CenterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Restriction.
        /// </summary>
        internal static string _CenterRestr {
            get {
                return ResourceManager.GetString("_CenterRestr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges Id.
        /// </summary>
        internal static string _ChargesId {
            get {
                return ResourceManager.GetString("_ChargesId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges Name.
        /// </summary>
        internal static string _ChargesName {
            get {
                return ResourceManager.GetString("_ChargesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string _Code {
            get {
                return ResourceManager.GetString("_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string _Country {
            get {
                return ResourceManager.GetString("_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string _CreateBy {
            get {
                return ResourceManager.GetString("_CreateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        internal static string _CreateDate {
            get {
                return ResourceManager.GetString("_CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Code.
        /// </summary>
        internal static string _CurrCode {
            get {
                return ResourceManager.GetString("_CurrCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string _Currency {
            get {
                return ResourceManager.GetString("_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Name.
        /// </summary>
        internal static string _CurrName {
            get {
                return ResourceManager.GetString("_CurrName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D/C.
        /// </summary>
        internal static string _DCDesc {
            get {
                return ResourceManager.GetString("_DCDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departement.
        /// </summary>
        internal static string _Departement {
            get {
                return ResourceManager.GetString("_Departement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Code.
        /// </summary>
        internal static string _DeptCode {
            get {
                return ResourceManager.GetString("_DeptCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Name.
        /// </summary>
        internal static string _DeptName {
            get {
                return ResourceManager.GetString("_DeptName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string _Desc {
            get {
                return ResourceManager.GetString("_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Inactive COA.
        /// </summary>
        internal static string _EnableCOA {
            get {
                return ResourceManager.GetString("_EnableCOA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found data by search text!!.
        /// </summary>
        internal static string _ErrLookup01 {
            get {
                return ResourceManager.GetString("_ErrLookup01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        internal static string _Floor {
            get {
                return ResourceManager.GetString("_Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor ID.
        /// </summary>
        internal static string _FloorId {
            get {
                return ResourceManager.GetString("_FloorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor Name.
        /// </summary>
        internal static string _FloorName {
            get {
                return ResourceManager.GetString("_FloorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GL Account.
        /// </summary>
        internal static string _GLAccount {
            get {
                return ResourceManager.GetString("_GLAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group of Account.
        /// </summary>
        internal static string _GOACode {
            get {
                return ResourceManager.GetString("_GOACode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group of Account Name.
        /// </summary>
        internal static string _GOAName {
            get {
                return ResourceManager.GetString("_GOAName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross.
        /// </summary>
        internal static string _Gross {
            get {
                return ResourceManager.GetString("_Gross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Group Code.
        /// </summary>
        internal static string _JrnlGrpCode {
            get {
                return ResourceManager.GetString("_JrnlGrpCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Group Name.
        /// </summary>
        internal static string _JrnlGrpName {
            get {
                return ResourceManager.GetString("_JrnlGrpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOB Code.
        /// </summary>
        internal static string _LOBCode {
            get {
                return ResourceManager.GetString("_LOBCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOB Name.
        /// </summary>
        internal static string _LOBName {
            get {
                return ResourceManager.GetString("_LOBName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Curr. Base Rate.
        /// </summary>
        internal static string _LocCurrBaseRate {
            get {
                return ResourceManager.GetString("_LocCurrBaseRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Currency Rate.
        /// </summary>
        internal static string _LocCurrRate {
            get {
                return ResourceManager.GetString("_LocCurrRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string _Name {
            get {
                return ResourceManager.GetString("_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net.
        /// </summary>
        internal static string _Net {
            get {
                return ResourceManager.GetString("_Net", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Selected Data Must City.
        /// </summary>
        internal static string _NotifGSL02000MustCity {
            get {
                return ResourceManager.GetString("_NotifGSL02000MustCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string _OkBtn {
            get {
                return ResourceManager.GetString("_OkBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Date.
        /// </summary>
        internal static string _RateDate {
            get {
                return ResourceManager.GetString("_RateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Type.
        /// </summary>
        internal static string _RateType {
            get {
                return ResourceManager.GetString("_RateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Type Code.
        /// </summary>
        internal static string _RateTypeCode {
            get {
                return ResourceManager.GetString("_RateTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate Type Name.
        /// </summary>
        internal static string _RateTypeName {
            get {
                return ResourceManager.GetString("_RateTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounding Mode.
        /// </summary>
        internal static string _RoundMode {
            get {
                return ResourceManager.GetString("_RoundMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rounding Unit.
        /// </summary>
        internal static string _RoundUnit {
            get {
                return ResourceManager.GetString("_RoundUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence.
        /// </summary>
        internal static string _Seq {
            get {
                return ResourceManager.GetString("_Seq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string _Status {
            get {
                return ResourceManager.GetString("_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbol.
        /// </summary>
        internal static string _Symbol {
            get {
                return ResourceManager.GetString("_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Date.
        /// </summary>
        internal static string _TaxDate {
            get {
                return ResourceManager.GetString("_TaxDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Out GL Account Name.
        /// </summary>
        internal static string _TaxGlAccountName {
            get {
                return ResourceManager.GetString("_TaxGlAccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax In GL Account No.
        /// </summary>
        internal static string _TaxGlAccountNo {
            get {
                return ResourceManager.GetString("_TaxGlAccountNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Id.
        /// </summary>
        internal static string _TaxId {
            get {
                return ResourceManager.GetString("_TaxId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Name.
        /// </summary>
        internal static string _TaxName {
            get {
                return ResourceManager.GetString("_TaxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax %.
        /// </summary>
        internal static string _TaxPersen {
            get {
                return ResourceManager.GetString("_TaxPersen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Type.
        /// </summary>
        internal static string _TaxType {
            get {
                return ResourceManager.GetString("_TaxType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term Of Payment Code.
        /// </summary>
        internal static string _TOPCode {
            get {
                return ResourceManager.GetString("_TOPCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOP Days.
        /// </summary>
        internal static string _TOPDays {
            get {
                return ResourceManager.GetString("_TOPDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term Of Payment Name.
        /// </summary>
        internal static string _TOPName {
            get {
                return ResourceManager.GetString("_TOPName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Category.
        /// </summary>
        internal static string _UnitCategory {
            get {
                return ResourceManager.GetString("_UnitCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Id.
        /// </summary>
        internal static string _UnitId {
            get {
                return ResourceManager.GetString("_UnitId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Name.
        /// </summary>
        internal static string _UnitName {
            get {
                return ResourceManager.GetString("_UnitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Type.
        /// </summary>
        internal static string _UnitType {
            get {
                return ResourceManager.GetString("_UnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit View.
        /// </summary>
        internal static string _UnitView {
            get {
                return ResourceManager.GetString("_UnitView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Type Category Id.
        /// </summary>
        internal static string _UntTypeCatId {
            get {
                return ResourceManager.GetString("_UntTypeCatId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Type Category Name.
        /// </summary>
        internal static string _UntTypeCatName {
            get {
                return ResourceManager.GetString("_UntTypeCatName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated By.
        /// </summary>
        internal static string _UpdateBy {
            get {
                return ResourceManager.GetString("_UpdateBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Date.
        /// </summary>
        internal static string _UpdateDate {
            get {
                return ResourceManager.GetString("_UpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id.
        /// </summary>
        internal static string _UserId {
            get {
                return ResourceManager.GetString("_UserId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        internal static string _UserName {
            get {
                return ResourceManager.GetString("_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Restriction.
        /// </summary>
        internal static string _UserRestr {
            get {
                return ResourceManager.GetString("_UserRestr", resourceCulture);
            }
        }
    }
}
