//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSP_AP_PRODUCT_ALLOCATION_UPLOADResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RSP_AP_PRODUCT_ALLOCATION_UPLOADResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RSP_AP_PRODUCT_ALLOCATION_UPLOADResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSP_AP_PRODUCT_ALLOCATION_UPLOADResources.RSP_AP_PRODUCT_ALLOCATION_UPLOADResourc" +
                            "es_msgrsc", typeof(RSP_AP_PRODUCT_ALLOCATION_UPLOADResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No. is mandatory.
        /// </summary>
        internal static string ACCOUNT_NO_EMPTY {
            get {
                return ResourceManager.GetString("ACCOUNT_NO_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No. is more than 20 characters.
        /// </summary>
        internal static string ACCOUNT_NO_LENGTH_EXCEEDED {
            get {
                return ResourceManager.GetString("ACCOUNT_NO_LENGTH_EXCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No. does not exist.
        /// </summary>
        internal static string ACCOUNT_NO_NOT_EXIST {
            get {
                return ResourceManager.GetString("ACCOUNT_NO_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated Allocation found for department mode ALL.
        /// </summary>
        internal static string ALLOCATION_DUPLICATE_ALL {
            get {
                return ResourceManager.GetString("ALLOCATION_DUPLICATE_ALL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicated Allocation found for department mode EACH.
        /// </summary>
        internal static string ALLOCATION_DUPLICATE_EACH {
            get {
                return ResourceManager.GetString("ALLOCATION_DUPLICATE_EACH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocation ID already exists.
        /// </summary>
        internal static string ALLOCATION_ID_ALREADY_EXIST {
            get {
                return ResourceManager.GetString("ALLOCATION_ID_ALREADY_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocation ID is mandatory.
        /// </summary>
        internal static string ALLOCATION_ID_EMPTY {
            get {
                return ResourceManager.GetString("ALLOCATION_ID_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocation ID is more than 20 characters.
        /// </summary>
        internal static string ALLOCATION_ID_LENGTH_EXCEEDED {
            get {
                return ResourceManager.GetString("ALLOCATION_ID_LENGTH_EXCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocation Name is mandatory.
        /// </summary>
        internal static string ALLOCATION_NAME_EMPTY {
            get {
                return ResourceManager.GetString("ALLOCATION_NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allocation Name is more than 50 characters.
        /// </summary>
        internal static string ALLOCATION_NAME_LENGTH_EXCEEDED {
            get {
                return ResourceManager.GetString("ALLOCATION_NAME_LENGTH_EXCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Code is mandatory.
        /// </summary>
        internal static string DEPARTMENT_CODE_EMPTY {
            get {
                return ResourceManager.GetString("DEPARTMENT_CODE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Code is more than 20 characters.
        /// </summary>
        internal static string DEPARTMENT_CODE_LENGTH_EXCEEDED {
            get {
                return ResourceManager.GetString("DEPARTMENT_CODE_LENGTH_EXCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department Code does not exist.
        /// </summary>
        internal static string DEPARTMENT_CODE_NOT_EXIST {
            get {
                return ResourceManager.GetString("DEPARTMENT_CODE_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DEPARTMENT_MODE_EMPTY {
            get {
                return ResourceManager.GetString("DEPARTMENT_MODE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Department Mode, valid value is ALL/EACH.
        /// </summary>
        internal static string DEPARTMENT_MODE_INVALID {
            get {
                return ResourceManager.GetString("DEPARTMENT_MODE_INVALID", resourceCulture);
            }
        }
    }
}
