//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LookupLMFrontResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LookupLMFrontResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LookupLMFrontResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LookupLMFrontResources.LookupLMFrontResources_msgrsc", typeof(LookupLMFrontResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges Id.
        /// </summary>
        internal static string _ChargesId {
            get {
                return ResourceManager.GetString("_ChargesId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges Name.
        /// </summary>
        internal static string _ChargesName {
            get {
                return ResourceManager.GetString("_ChargesName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges Type Description.
        /// </summary>
        internal static string _ChargesTypeDesc {
            get {
                return ResourceManager.GetString("_ChargesTypeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charges Type.
        /// </summary>
        internal static string _ChargeType {
            get {
                return ResourceManager.GetString("_ChargeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string _Dept {
            get {
                return ResourceManager.GetString("_Dept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Id.
        /// </summary>
        internal static string _discountId {
            get {
                return ResourceManager.GetString("_discountId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Name.
        /// </summary>
        internal static string _discountName {
            get {
                return ResourceManager.GetString("_discountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Type.
        /// </summary>
        internal static string _discountType {
            get {
                return ResourceManager.GetString("_discountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string _Email {
            get {
                return ResourceManager.GetString("_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found data by search text!!.
        /// </summary>
        internal static string _ErrLookup01 {
            get {
                return ResourceManager.GetString("_ErrLookup01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone 1.
        /// </summary>
        internal static string _Phone {
            get {
                return ResourceManager.GetString("_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesman Id.
        /// </summary>
        internal static string _SalesmanId {
            get {
                return ResourceManager.GetString("_SalesmanId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesman Name.
        /// </summary>
        internal static string _SalesmanName {
            get {
                return ResourceManager.GetString("_SalesmanName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor Id.
        /// </summary>
        internal static string _SPVId {
            get {
                return ResourceManager.GetString("_SPVId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supervisor Name.
        /// </summary>
        internal static string _SPVName {
            get {
                return ResourceManager.GetString("_SPVName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax %.
        /// </summary>
        internal static string _Tax_ {
            get {
                return ResourceManager.GetString("_Tax%", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Id.
        /// </summary>
        internal static string _TaxId {
            get {
                return ResourceManager.GetString("_TaxId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Name.
        /// </summary>
        internal static string _TaxName {
            get {
                return ResourceManager.GetString("_TaxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Category.
        /// </summary>
        internal static string _TenantCat {
            get {
                return ResourceManager.GetString("_TenantCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Group.
        /// </summary>
        internal static string _TenantGroup {
            get {
                return ResourceManager.GetString("_TenantGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Id.
        /// </summary>
        internal static string _TenantId {
            get {
                return ResourceManager.GetString("_TenantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Name.
        /// </summary>
        internal static string _TenantName {
            get {
                return ResourceManager.GetString("_TenantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Type.
        /// </summary>
        internal static string _TenantType {
            get {
                return ResourceManager.GetString("_TenantType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        internal static string _Units {
            get {
                return ResourceManager.GetString("_Units", resourceCulture);
            }
        }
    }
}
