//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GLR00300FrontResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GLR00300FrontResources_msgrsc___Copy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GLR00300FrontResources_msgrsc___Copy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GLR00300FrontResources.GLR00300FrontResources_msgrsc - Copy", typeof(GLR00300FrontResources_msgrsc___Copy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string _Account {
            get {
                return ResourceManager.GetString("_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget No..
        /// </summary>
        internal static string _BudgetNo {
            get {
                return ResourceManager.GetString("_BudgetNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Type.
        /// </summary>
        internal static string _CurrencyType {
            get {
                return ResourceManager.GetString("_CurrencyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string _From {
            get {
                return ResourceManager.GetString("_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Adjustment Mode.
        /// </summary>
        internal static string _JournalAdjMode {
            get {
                return ResourceManager.GetString("_JournalAdjMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        internal static string _Period {
            get {
                return ResourceManager.GetString("_Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Budget.
        /// </summary>
        internal static string _PrintBudget {
            get {
                return ResourceManager.GetString("_PrintBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print By Center.
        /// </summary>
        internal static string _PrintByCenter {
            get {
                return ResourceManager.GetString("_PrintByCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Method.
        /// </summary>
        internal static string _PrintMethod {
            get {
                return ResourceManager.GetString("_PrintMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReportOption.
        /// </summary>
        internal static string _ReportOption {
            get {
                return ResourceManager.GetString("_ReportOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trial  Balance Type.
        /// </summary>
        internal static string _TBType {
            get {
                return ResourceManager.GetString("_TBType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string _To {
            get {
                return ResourceManager.GetString("_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string _Year {
            get {
                return ResourceManager.GetString("_Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select From Center Code.!.
        /// </summary>
        internal static string Error_01 {
            get {
                return ResourceManager.GetString("Error_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select To Center Code.!.
        /// </summary>
        internal static string Error_02 {
            get {
                return ResourceManager.GetString("Error_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Budget No.!.
        /// </summary>
        internal static string Error_03 {
            get {
                return ResourceManager.GetString("Error_03", resourceCulture);
            }
        }
    }
}
