//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GLB00200FrontResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GLB00200FrontResources_msgrsc___Copy {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GLB00200FrontResources_msgrsc___Copy() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GLB00200FrontResources.GLB00200FrontResources_msgrsc - Copy", typeof(GLB00200FrontResources_msgrsc___Copy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        internal static string _AccName {
            get {
                return ResourceManager.GetString("_AccName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No..
        /// </summary>
        internal static string _AccNo {
            get {
                return ResourceManager.GetString("_AccNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string _Amount {
            get {
                return ResourceManager.GetString("_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Amount.
        /// </summary>
        internal static string _BaseAmount {
            get {
                return ResourceManager.GetString("_BaseAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base Currency.
        /// </summary>
        internal static string _BaseCurrency {
            get {
                return ResourceManager.GetString("_BaseCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        internal static string _Center {
            get {
                return ResourceManager.GetString("_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        internal static string _Credit {
            get {
                return ResourceManager.GetString("_Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string _Currency {
            get {
                return ResourceManager.GetString("_Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D/C.
        /// </summary>
        internal static string _DC {
            get {
                return ResourceManager.GetString("_DC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit.
        /// </summary>
        internal static string _Debit {
            get {
                return ResourceManager.GetString("_Debit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departement.
        /// </summary>
        internal static string _Dept {
            get {
                return ResourceManager.GetString("_Dept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string _Desc {
            get {
                return ResourceManager.GetString("_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        internal static string _Detail {
            get {
                return ResourceManager.GetString("_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Date.
        /// </summary>
        internal static string _DocDate {
            get {
                return ResourceManager.GetString("_DocDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docoment No..
        /// </summary>
        internal static string _DocNo {
            get {
                return ResourceManager.GetString("_DocNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Period :.
        /// </summary>
        internal static string _JournalPeriod {
            get {
                return ResourceManager.GetString("_JournalPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Amount.
        /// </summary>
        internal static string _LocAmount {
            get {
                return ResourceManager.GetString("_LocAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Currency.
        /// </summary>
        internal static string _LocCurrency {
            get {
                return ResourceManager.GetString("_LocCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        internal static string _No {
            get {
                return ResourceManager.GetString("_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        internal static string _Process {
            get {
                return ResourceManager.GetString("_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference No.:.
        /// </summary>
        internal static string _ReferenceNo {
            get {
                return ResourceManager.GetString("_ReferenceNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Ref. No..
        /// </summary>
        internal static string _RefNo {
            get {
                return ResourceManager.GetString("_RefNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reversing Date.
        /// </summary>
        internal static string _ReversDate {
            get {
                return ResourceManager.GetString("_ReversDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string _Search {
            get {
                return ResourceManager.GetString("_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All.
        /// </summary>
        internal static string _ShowAll {
            get {
                return ResourceManager.GetString("_ShowAll", resourceCulture);
            }
        }
    }
}
