//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSP_AP_PRODUCT_UPLOADResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RSP_AP_PRODUCT_UPLOADResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RSP_AP_PRODUCT_UPLOADResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RSP_AP_PRODUCT_UPLOADResources.RSP_AP_PRODUCT_UPLOADResources_msgrsc", typeof(RSP_AP_PRODUCT_UPLOADResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product ID already exists.
        /// </summary>
        internal static string ALIAS_ID_ALREADY_EXIST {
            get {
                return ResourceManager.GetString("ALIAS_ID_ALREADY_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product ID is more than 20 characters.
        /// </summary>
        internal static string ALIAS_ID_LENGTH_EXCEEDED {
            get {
                return ResourceManager.GetString("ALIAS_ID_LENGTH_EXCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PRODUCT Name is more than 50 characters.
        /// </summary>
        internal static string ALIAS_NAME_LENGTH_EXCEEDED {
            get {
                return ResourceManager.GetString("ALIAS_NAME_LENGTH_EXCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Flag is mandatory.
        /// </summary>
        internal static string BUY_FLAG_EMPTY {
            get {
                return ResourceManager.GetString("BUY_FLAG_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Buy Flag value, valid value is Yes/No.
        /// </summary>
        internal static string BUY_FLAG_INVALID {
            get {
                return ResourceManager.GetString("BUY_FLAG_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Flag is more than 10 characters.
        /// </summary>
        internal static string BUY_FLAG_LENGTH_EXCEEDED {
            get {
                return ResourceManager.GetString("BUY_FLAG_LENGTH_EXCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category ID is mandatory.
        /// </summary>
        internal static string CATEGORY_ID_EMPTY {
            get {
                return ResourceManager.GetString("CATEGORY_ID_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category ID is more than 20 characters.
        /// </summary>
        internal static string CATEGORY_ID_LENGTH_EXCEEDED {
            get {
                return ResourceManager.GetString("CATEGORY_ID_LENGTH_EXCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category ID does not exist.
        /// </summary>
        internal static string CATEGORY_ID_NOT_EXIST {
            get {
                return ResourceManager.GetString("CATEGORY_ID_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Conversion 1, Conversion 1 value must be &gt; 0.
        /// </summary>
        internal static string CONVERSION1_INVALID {
            get {
                return ResourceManager.GetString("CONVERSION1_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Conversion 2, Conversion 2 value must be &gt; 0.
        /// </summary>
        internal static string CONVERSION2_INVALID {
            get {
                return ResourceManager.GetString("CONVERSION2_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN Flag is mandatory.
        /// </summary>
        internal static string IN_FLAG_EMPTY {
            get {
                return ResourceManager.GetString("IN_FLAG_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid IN Flag value, valid value is Yes/No.
        /// </summary>
        internal static string IN_FLAG_INVALID {
            get {
                return ResourceManager.GetString("IN_FLAG_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IN Flag is more than 10 characters.
        /// </summary>
        internal static string IN_FLAG_LENGTH_EXCEEDED {
            get {
                return ResourceManager.GetString("IN_FLAG_LENGTH_EXCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Group ID is mandatory.
        /// </summary>
        internal static string JOURNAL_GROUP_ID_EMPTY {
            get {
                return ResourceManager.GetString("JOURNAL_GROUP_ID_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Group ID is more than 8 characters.
        /// </summary>
        internal static string JOURNAL_GROUP_ID_LENGTH_EXCEEDED {
            get {
                return ResourceManager.GetString("JOURNAL_GROUP_ID_LENGTH_EXCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Group ID does not exist.
        /// </summary>
        internal static string JOURNAL_GROUP_ID_NOT_EXIST {
            get {
                return ResourceManager.GetString("JOURNAL_GROUP_ID_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUT Flag is mandatory.
        /// </summary>
        internal static string OUT_FLAG_EMPTY {
            get {
                return ResourceManager.GetString("OUT_FLAG_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid OUT Flag value, valid value is Yes/No.
        /// </summary>
        internal static string OUT_FLAG_INVALID {
            get {
                return ResourceManager.GetString("OUT_FLAG_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUT Flag is more than 10 characters.
        /// </summary>
        internal static string OUT_FLAG_LENGTH_EXCEEDED {
            get {
                return ResourceManager.GetString("OUT_FLAG_LENGTH_EXCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product ID already exists.
        /// </summary>
        internal static string PRODUCT_ID_ALREADY_EXIST {
            get {
                return ResourceManager.GetString("PRODUCT_ID_ALREADY_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product ID is mandatory.
        /// </summary>
        internal static string PRODUCT_ID_EMPTY {
            get {
                return ResourceManager.GetString("PRODUCT_ID_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product ID is more than 20 characters.
        /// </summary>
        internal static string PRODUCT_ID_LENGTH_EXCEEDED {
            get {
                return ResourceManager.GetString("PRODUCT_ID_LENGTH_EXCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name is mandatory.
        /// </summary>
        internal static string PRODUCT_NAME_EMPTY {
            get {
                return ResourceManager.GetString("PRODUCT_NAME_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name is more than 50 characters.
        /// </summary>
        internal static string PRODUCT_NAME_LENGTH_EXCEEDED {
            get {
                return ResourceManager.GetString("PRODUCT_NAME_LENGTH_EXCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Unit is mandatory.
        /// </summary>
        internal static string PURCHASE_UNIT_EMPTY {
            get {
                return ResourceManager.GetString("PURCHASE_UNIT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Purchase Unit, Purchase Unit must be either Unit 1/Unit 2/Unit 3.
        /// </summary>
        internal static string PURCHASE_UNIT_INVALID {
            get {
                return ResourceManager.GetString("PURCHASE_UNIT_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Unit is more than 10 characters.
        /// </summary>
        internal static string PURCHASE_UNIT_LENGTH_EXCEEDED {
            get {
                return ResourceManager.GetString("PURCHASE_UNIT_LENGTH_EXCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell Flag is mandatory.
        /// </summary>
        internal static string SELL_FLAG_EMPTY {
            get {
                return ResourceManager.GetString("SELL_FLAG_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Sell Flag value, valid value is Yes/No.
        /// </summary>
        internal static string SELL_FLAG_INVALID {
            get {
                return ResourceManager.GetString("SELL_FLAG_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell Flag is more than 10 characters.
        /// </summary>
        internal static string SELL_FLAG_LENGTH_EXCEEDED {
            get {
                return ResourceManager.GetString("SELL_FLAG_LENGTH_EXCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax ID is more than 20 characters.
        /// </summary>
        internal static string TAX_ID_LENGTH_EXCEEDED {
            get {
                return ResourceManager.GetString("TAX_ID_LENGTH_EXCEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax ID does not exist.
        /// </summary>
        internal static string TAX_ID_NOT_EXIST {
            get {
                return ResourceManager.GetString("TAX_ID_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxable is mandatory.
        /// </summary>
        internal static string TAXABLE_EMPTY {
            get {
                return ResourceManager.GetString("TAXABLE_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Taxable value, valid value is Yes/No.
        /// </summary>
        internal static string TAXABLE_INVALID {
            get {
                return ResourceManager.GetString("TAXABLE_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit 1 is mandatory.
        /// </summary>
        internal static string UNIT1_EMPTY {
            get {
                return ResourceManager.GetString("UNIT1_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit 1 is more than 10 characters.
        /// </summary>
        internal static string UNIT1_LENGTH_EXCEEDED {
            get {
                return ResourceManager.GetString("UNIT1_LENGTH_EXCEEDED", resourceCulture);
            }
        }
    }
}
