//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMM02500FrontResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LMM02500FrontResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LMM02500FrontResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LMM02500FrontResources.LMM02500FrontResources_msgrsc", typeof(LMM02500FrontResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string _Address {
            get {
                return ResourceManager.GetString("_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string _Cancel {
            get {
                return ResourceManager.GetString("_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string _CreatedBy {
            get {
                return ResourceManager.GetString("_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        internal static string _CreatedDate {
            get {
                return ResourceManager.GetString("_CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string _Date {
            get {
                return ResourceManager.GetString("_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string _Email {
            get {
                return ResourceManager.GetString("_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Tenant Category.
        /// </summary>
        internal static string _FromTenantCategory {
            get {
                return ResourceManager.GetString("_FromTenantCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Expired Date.
        /// </summary>
        internal static string _IdExpiredDate {
            get {
                return ResourceManager.GetString("_IdExpiredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Number.
        /// </summary>
        internal static string _IdNumber {
            get {
                return ResourceManager.GetString("_IdNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Type.
        /// </summary>
        internal static string _IdType {
            get {
                return ResourceManager.GetString("_IdType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit Amount.
        /// </summary>
        internal static string _LimitAmount {
            get {
                return ResourceManager.GetString("_LimitAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No (1).
        /// </summary>
        internal static string _MobileNo1 {
            get {
                return ResourceManager.GetString("_MobileNo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile No (2).
        /// </summary>
        internal static string _MobileNo2 {
            get {
                return ResourceManager.GetString("_MobileNo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move.
        /// </summary>
        internal static string _Move {
            get {
                return ResourceManager.GetString("_Move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string _Next {
            get {
                return ResourceManager.GetString("_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone No (1).
        /// </summary>
        internal static string _Phone1 {
            get {
                return ResourceManager.GetString("_Phone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone No (2).
        /// </summary>
        internal static string _Phone2 {
            get {
                return ResourceManager.GetString("_Phone2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone 1.
        /// </summary>
        internal static string _PhoneTenant1 {
            get {
                return ResourceManager.GetString("_PhoneTenant1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIC Email.
        /// </summary>
        internal static string _PICEmail {
            get {
                return ResourceManager.GetString("_PICEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIC Name.
        /// </summary>
        internal static string _PICName {
            get {
                return ResourceManager.GetString("_PICName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIC Mobile No (1).
        /// </summary>
        internal static string _PICPhone1 {
            get {
                return ResourceManager.GetString("_PICPhone1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIC Position.
        /// </summary>
        internal static string _PICPosition {
            get {
                return ResourceManager.GetString("_PICPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        internal static string _Process {
            get {
                return ResourceManager.GetString("_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROPERTY.
        /// </summary>
        internal static string _PropertyUppercase {
            get {
                return ResourceManager.GetString("_PropertyUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receipt Payment with Withholding Tax(PPh) Deduction.
        /// </summary>
        internal static string _ReceiptPayment {
            get {
                return ResourceManager.GetString("_ReceiptPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Code.
        /// </summary>
        internal static string _TaxCode {
            get {
                return ResourceManager.GetString("_TaxCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Id.
        /// </summary>
        internal static string _TaxId {
            get {
                return ResourceManager.GetString("_TaxId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Name.
        /// </summary>
        internal static string _TaxName {
            get {
                return ResourceManager.GetString("_TaxName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Category.
        /// </summary>
        internal static string _TenantCategory {
            get {
                return ResourceManager.GetString("_TenantCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Group.
        /// </summary>
        internal static string _TenantGroup {
            get {
                return ResourceManager.GetString("_TenantGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Group Id.
        /// </summary>
        internal static string _TenantGroupId {
            get {
                return ResourceManager.GetString("_TenantGroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Group Name.
        /// </summary>
        internal static string _TenantGroupName {
            get {
                return ResourceManager.GetString("_TenantGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Id.
        /// </summary>
        internal static string _TenantId {
            get {
                return ResourceManager.GetString("_TenantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Name.
        /// </summary>
        internal static string _TenantName {
            get {
                return ResourceManager.GetString("_TenantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Type.
        /// </summary>
        internal static string _TenantType {
            get {
                return ResourceManager.GetString("_TenantType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Tenant Category.
        /// </summary>
        internal static string _ToTenantCategory {
            get {
                return ResourceManager.GetString("_ToTenantCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string _Type {
            get {
                return ResourceManager.GetString("_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units.
        /// </summary>
        internal static string _Units {
            get {
                return ResourceManager.GetString("_Units", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated By.
        /// </summary>
        internal static string _UpdatedBy {
            get {
                return ResourceManager.GetString("_UpdatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Date.
        /// </summary>
        internal static string _UpdatedDate {
            get {
                return ResourceManager.GetString("_UpdatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Group Tax Info.
        /// </summary>
        internal static string _UseGroupTaxInfo {
            get {
                return ResourceManager.GetString("_UseGroupTaxInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address cannot be null..
        /// </summary>
        internal static string ValidationAddress {
            get {
                return ResourceManager.GetString("ValidationAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIC Name cannot be null..
        /// </summary>
        internal static string ValidationPICName {
            get {
                return ResourceManager.GetString("ValidationPICName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Group Id cannot be null..
        /// </summary>
        internal static string ValidationTenantGroupID {
            get {
                return ResourceManager.GetString("ValidationTenantGroupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenant Group Name cannot be null..
        /// </summary>
        internal static string ValidationTenantGroupName {
            get {
                return ResourceManager.GetString("ValidationTenantGroupName", resourceCulture);
            }
        }
    }
}
