---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: otl-api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: otl-api
    spec:
      containers:
      - name: otl-api
        image: dockerguntech/otl-api
        ports:
        - containerPort: 80
        env:
        - name: R_DBSECTION__R_DBCONFIGS__0__CONNECTIONSTRING
          value: server=host.docker.internal,57746;Initial Catalog=TestDB;User ID=sa;Password=F8093F6CAEAFDDC975507D0EEBD760E4;
        - name: SERILOG__WRITETO__0__NAME
          value: OpenTelemetry
        - name: SERILOG__WRITETO__0__ARGS__ENDPOINT
          value: http://otel-coll:4317
        - name: SERILOG__WRITETO__0__ARGS__PROTOCOL
          value: Grpc
        - name: OPENTELEMETRY__OTLP__ENDPOINT
          value: http://otel-coll:4317
  selector:
    matchLabels:
      app: otl-api
---
apiVersion: v1
kind: Service
metadata:
  name: otl-api
spec:
  type: LoadBalancer
  ports:
  - port: 5901
    targetPort: 80
  selector:
    app: otl-api