//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMM06000FrontResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LMM06000FrontResources_msgrsc {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LMM06000FrontResources_msgrsc() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LMM06000FrontResources.LMM06000FrontResources_msgrsc", typeof(LMM06000FrontResources_msgrsc).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string _Active {
            get {
                return ResourceManager.GetString("_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Credit.
        /// </summary>
        internal static string _BankCredit {
            get {
                return ResourceManager.GetString("_BankCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Rule*.
        /// </summary>
        internal static string _BillingRule {
            get {
                return ResourceManager.GetString("_BillingRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Fee.
        /// </summary>
        internal static string _BookingFee {
            get {
                return ResourceManager.GetString("_BookingFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge Id*.
        /// </summary>
        internal static string _ChargeId {
            get {
                return ResourceManager.GetString("_ChargeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Rule Code.
        /// </summary>
        internal static string _ColumnBillingCode {
            get {
                return ResourceManager.GetString("_ColumnBillingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Rule Code.
        /// </summary>
        internal static string _ColumnBillingName {
            get {
                return ResourceManager.GetString("_ColumnBillingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        internal static string _CreatedBy {
            get {
                return ResourceManager.GetString("_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Date.
        /// </summary>
        internal static string _CreatedDate {
            get {
                return ResourceManager.GetString("_CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval.
        /// </summary>
        internal static string _DpInterval {
            get {
                return ResourceManager.GetString("_DpInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installment.
        /// </summary>
        internal static string _Installment {
            get {
                return ResourceManager.GetString("_Installment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval*.
        /// </summary>
        internal static string _Interval {
            get {
                return ResourceManager.GetString("_Interval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %.
        /// </summary>
        internal static string _Percent {
            get {
                return ResourceManager.GetString("_Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage*.
        /// </summary>
        internal static string _Percentage {
            get {
                return ResourceManager.GetString("_Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        internal static string _Period {
            get {
                return ResourceManager.GetString("_Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period Mode*.
        /// </summary>
        internal static string _PeriodMode {
            get {
                return ResourceManager.GetString("_PeriodMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PROPERTY.
        /// </summary>
        internal static string _Prop {
            get {
                return ResourceManager.GetString("_Prop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Type Category.
        /// </summary>
        internal static string _UnitType {
            get {
                return ResourceManager.GetString("_UnitType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated By.
        /// </summary>
        internal static string _UpdBy {
            get {
                return ResourceManager.GetString("_UpdBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated Date.
        /// </summary>
        internal static string _UpdDate {
            get {
                return ResourceManager.GetString("_UpdDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With DP.
        /// </summary>
        internal static string _WithDp {
            get {
                return ResourceManager.GetString("_WithDp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Rule Code is required..
        /// </summary>
        internal static string Error_01 {
            get {
                return ResourceManager.GetString("Error_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing Rule Name is required..
        /// </summary>
        internal static string Error_02 {
            get {
                return ResourceManager.GetString("Error_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge Id Booking Fee is required..
        /// </summary>
        internal static string Error_03 {
            get {
                return ResourceManager.GetString("Error_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period Mode With Dp is required..
        /// </summary>
        internal static string Error_04 {
            get {
                return ResourceManager.GetString("Error_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge Id With DP is required..
        /// </summary>
        internal static string Error_05 {
            get {
                return ResourceManager.GetString("Error_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period Mode Installment is required.
        /// </summary>
        internal static string Error_06 {
            get {
                return ResourceManager.GetString("Error_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge Id Installment is required..
        /// </summary>
        internal static string Error_07 {
            get {
                return ResourceManager.GetString("Error_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Valueis required..
        /// </summary>
        internal static string Error_08 {
            get {
                return ResourceManager.GetString("Error_08", resourceCulture);
            }
        }
    }
}
